version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    env_file:
      - ./gateway/.env
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - redis
      - backend-service
    restart: unless-stopped

  backend-service:
    build:
      context: ./backend-service
      dockerfile: Dockerfile
    env_file:
      - ./backend-service/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    restart: unless-stopped

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    env_file:
      - ./dashboard/.env
    ports:
      - "3000:3000"
    depends_on:
      - gateway
    restart: unless-stopped

  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    restart: unless-stopped

volumes:
  mongo-data: