name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd gateway
          npm install
          cd ../dashboard
          npm install

      - name: Run tests
        run: |
          cd gateway
          npm test
          cd ../dashboard
          npm test

      - name: Build Docker images
        run: |
          docker build -t secure-api-gateway/gateway ./gateway
          docker build -t secure-api-gateway/dashboard ./dashboard

      - name: Push Docker images
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push secure-api-gateway/gateway
          docker push secure-api-gateway/dashboard